### ISSUE TITLE
특정 투어의 지도 뷰에서

### ISSUE THREAD

**Issue by WannaBeSuperteur** [ProjectInTheClass/TwithS#10]
Map View를 테이블 뷰 안의 셀에 삽입하는 것보다는 테이블 뷰 바깥쪽(위쪽이나 아래쪽)에 따로 삽입하는 것이 좋을 것 같은데, 의견을 요청합니다.

**Comment by sambong0113** [comment]
맵뷰가 어떤 것을 의미하는지 잘 모르겠습니다. 구체적인 설명이 필요합니다.

**Comment by WannaBeSuperteur** [comment]
도구 모음에 있는 Map Kit View를 의미합니다.

**Comment by sambong0113** [comment]
맵뷰를 사용하는 곳이 어딘지를 묻는 것이었습니다.

**Comment by WannaBeSuperteur** [comment]
Map View를 사용하는 곳은 특정 투어에 대한 지도를 보여 주는 씬입니다.
잘못 이해해서 죄송합니다.
