### ISSUE TITLE
투어의 테마 번호를 정하는 방법

### ISSUE THREAD

**Issue by WannaBeSuperteur** [ProjectInTheClass/TwithS#8]
투어의 테마 번호를 어떻게 정할지 의견 부탁드립니다.
채택된 의견에 따라 더미 데이터를 일부 수정하고, 테마와 테마 번호를 연결시키는 함수를 추가하겠습니다.

(예: 0: 맛집 / 1: 액티비티 ...)

**Comment by sambong0113** [comment]
개인적인 의견으로는 투어번호를 우선 생략하고 핵심적인 기능을 구현마친 후 생각해는 것이 좋을듯 합니다.
