### ISSUE TITLE
랜드마크 정보 뷰를 어떻게 할 것인가?

### ISSUE THREAD

**Issue by WannaBeSuperteur** [ProjectInTheClass/TwithS#9]
Main.storyboard의 오른쪽 윗부분에 있는 2개의 뷰 중 특정 투어의 정보를 표시하는 뷰는 테이블 뷰로 되어 있는데, 특정 랜드마크의 정보를 표시하는 뷰는 그렇게 되어 있지 않습니다.
랜드마크 정보 뷰도 투어에 대한 정보 뷰처럼 테이블 뷰로 하고 싶은데, 의견을 요청합니다.

**Comment by sambong0113** [comment]
어떤 뷰로 할지는 구현하기 나름이라 생각합니다. 편한대로 하면 될 것 같습니다.
